name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pr_checks:
    name: PR Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: "latest"

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check dependencies
        run: pnpm depcheck

      - name: Lint
        run: pnpm lint

      - name: Build package
        run: pnpm build

      - name: Run tests
        run: pnpm test
